version: '3.7'

services:
  db:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - "database:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: vogdb
      MYSQL_USER: vog
      MYSQL_PASSWORD: password

  dbtest:
    image: mysql:8
    restart: unless-stopped
    volumes:
      - "database:/var/lib/mysql_test"
    ports:
      - "4000:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: vogdb_test
      MYSQL_USER: vog
      MYSQL_PASSWORD: password

  app:
    init: true
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - db
      - dbtest
    volumes:
      - "data:/data"
    ports:
      - "8000:8000"
    environment:
      VOG_DATA: /data/vog
      NCBI_DATA: /data/ncbi
      MYSQL_HOST: db
      MYSQL_DATABASE: vogdb
      MYSQL_USER: vog
      MYSQL_PASSWORD: password

      VOG_DATA_TEST: /data/vog_test
      MYSQL_DATABASE_TEST: vogdb_test
      MYSQL_HOST_TEST: dbtest
    command: uvicorn

volumes:
  database:
  data:
